version: "3.7"

services:
    jekyll:
        image: jekyll/jekyll
        command: jekyll serve --watch --drafts
        container_name: blog
        ports: 
            - "80:4000"
        volumes: 
            - .:/srv/jekyll